version: '3.8'

services:
  node-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    
  python-server:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - .:/app